### ISSUE TITLE
ASIO Downloader & "Installer"

### ISSUE THREAD

**Issue by mitchmindtree** [freesig/cpal#2]
A simple rust crate that can be used in build scripts to automatically download and "install" the audio SDK into a reasonable location.

1. Downloads [the SDK zip from steinberg](http://www.steinberg.net/sdk_downloads/ASIOSDK2.3.1.zip).
2. Unzip the SDK.
3. Copy unzipped directory into `~/.asio/`. Use `dirs` crate to get the home directory in a reliable way.
4. Check to see if `CPAL_ASIO_DIR` is set. If not, set it to `~/.asio/`.

**Comment by mitchmindtree** [comment]
This has been implemented [here](https://github.com/mitchmindtree/asio_sdk_fetcher) but lacks the final step of setting the `CPAL_ASIO_DIR` env var. Not sure if there is a reliable cross-platform way of setting this in the user's configuration files - it might be best if we let the CPAL windows ASIO buildscript check for this folder and then set it in the case that it isn't already set.

**Comment by freesig** [comment]
Yeh in the build script if it's not set we could default to checking home/.asio/ 
Then is that fails we could print a nice error explaining how to install it with this crate
